export const sample_foods:any[]=[
    {
        id:'1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'2',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
      },
      {
        id:'3',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
      },
      {
        id:'4',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/food-4.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id:'5',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
      },
      {
        id:'6',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'7',
        name: 'Latte',
        price: 9,
        cookTime: '10-15',
        favorite: true,
        origins: ['America'],
        stars: 4.0,
        imageUrl: 'assets/icecoffee-6.jpg',
        tags: ['ColdDrinks', 'iceCoffee'],
      },
      {
        id:'8',
        name: 'Ice Chocolate',
        price: 11,
        cookTime: '10-15',
        favorite: false,
        origins: ['Belgium'],
        stars: 4.0,
        imageUrl: 'assets/icecoffee-1.jpg',
        tags: ['ColdDrinks', 'iceCoffee'],
      },

      {
        id:'9',
        name: 'Ice Moka',
        price: 15,
        cookTime: '10-15',
        favorite: false,
        origins: ['Tokyo'],
        stars: 4.0,
        imageUrl: 'assets/icecoffee-2.jpg',
        tags: ['ColdDrinks', 'iceCoffee'],
      },
      
      {
        id:'10',
        name: 'Ice Coffee Classic',
        price: 8,
        cookTime: '10-12',
        favorite: true,
        origins: ['London'],
        stars: 4.5,
        imageUrl: 'assets/icecoffe-5.png',
        tags: ['ColdDrinks', 'iceCoffee'],
      },
      {
        id:'11',
        name: 'Espresso Frappuccino',
        price: 13,
        cookTime: '10-12',
        favorite: false,
        origins: ['Chicago'],
        stars: 4.0,
        imageUrl: 'assets/icecoffee-3.jpg',
        tags: ['ColdDrinks', 'iceCoffee'],
      },
      {
        id:'12',
        name: 'Chocolate Cream ',
        price: 10,
        cookTime: '10-12',
        favorite: false,
        origins: ['Chicago'],
        stars: 3.5,
        imageUrl: 'assets/icecoffee-4.png',
        tags: ['ColdDrinks', 'iceCoffee'],
      },
      {
        id:'13',
        name: 'CheeseCake ',
        price: 20,
        cookTime: '15-20',
        favorite: true,
        origins: ['Japan'],
        stars: 4.5,
        imageUrl: 'assets/Sweets-1.png',
        tags: ['Sweets'],
      },
      {
        id:'14',
        name: 'Chocolate Cake ',
        price: 23,
        cookTime: '20-30',
        favorite: false,
        origins: ['Belgium'],
        stars: 4.0,
        imageUrl: 'assets/Sweets-2.png',
        tags: ['Sweets','Chocolate'],
      },
      {
        id:'15',
        name: 'Tiramisu Cake',
        price: 18,
        cookTime: '10-18',
        favorite: true,
        origins: ['Italy'],
        stars: 4.8,
        imageUrl: 'assets/Sweets-3.png',
        tags: ['Sweets'],
      },
      {
        id:'16',
        name: 'Molten Cake',
        price: 15.5,
        cookTime: '10-18',
        favorite: false,
        origins: ['France','Paris'],
        stars: 3.8,
        imageUrl: 'assets/Sweets-4.png',
        tags: ['Sweets','Chocolate'],
      },
      {
        id:'17',
        name: 'Red Velvet Cake',
        price: 18,
        cookTime: '15-20',
        favorite: true,
        origins: ['America'],
        stars: 4.0,
        imageUrl: 'assets/Sweets-5.png',
        tags: ['Sweets'],
      },
      {
        id:'18',
        name: 'Waffles',
        price: 12,
        cookTime: '15-20',
        favorite: false,
        origins: ['Mexican'],
        stars: 4.3,
        imageUrl: 'assets/Sweets-6.png',
        tags: ['Sweets'],
      },


]

export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
  {name : 'ColdDrinks', count:6},
  {name : 'Sweets', count:6}
];
export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
  {
    name: "Ghadeer Mohamed",
    email: "ghadeer@gmail.com",
    password: "12345",
    address: "Paris",
    isAdmin: false,
  },
];
